// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4lsewLEp29aKrUPSov3z7AueTxVJ0Ag',
    appId: '1:231471483797:web:122912247566d5b2ae449c',
    messagingSenderId: '231471483797',
    projectId: 'fir-task-7f232',
    authDomain: 'fir-task-7f232.firebaseapp.com',
    storageBucket: 'fir-task-7f232.appspot.com',
    measurementId: 'G-GYKYVM1NNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtOMFxNge3oFcOuyECV3HhkMUAWk1inyw',
    appId: '1:231471483797:android:34724d1c43f3e08cae449c',
    messagingSenderId: '231471483797',
    projectId: 'fir-task-7f232',
    storageBucket: 'fir-task-7f232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBChWw9og8y_ea5udhhuEIuLDlltdpaJCY',
    appId: '1:231471483797:ios:90b03da042f9367fae449c',
    messagingSenderId: '231471483797',
    projectId: 'fir-task-7f232',
    storageBucket: 'fir-task-7f232.appspot.com',
    iosBundleId: 'com.example.firebaseTaskOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBChWw9og8y_ea5udhhuEIuLDlltdpaJCY',
    appId: '1:231471483797:ios:90b03da042f9367fae449c',
    messagingSenderId: '231471483797',
    projectId: 'fir-task-7f232',
    storageBucket: 'fir-task-7f232.appspot.com',
    iosBundleId: 'com.example.firebaseTaskOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu4lsewLEp29aKrUPSov3z7AueTxVJ0Ag',
    appId: '1:231471483797:web:bb4488385997fd89ae449c',
    messagingSenderId: '231471483797',
    projectId: 'fir-task-7f232',
    authDomain: 'fir-task-7f232.firebaseapp.com',
    storageBucket: 'fir-task-7f232.appspot.com',
    measurementId: 'G-CE9SCBMR9E',
  );
}
